{% set name = "taxbrain" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PSLmodels/Tax-Brain/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2fd692e6e4071aba790e8ce8f0db4a3066857e39e2d64b3bc36ba74649eff39a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - taxbrain = taxbrain.cli:cli_main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - taxcalc >=3.0.0
    - behresp >=0.11.0
    - dask
    - bokeh
    - markdown
    - tabulate
    - pypandoc
    - matplotlib-base
    - numpy >=1.14

test:
  imports:
    - taxbrain

about:
  home: https://github.com/PSLmodels/Tax-Brain
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'A Python package that integrates tax models under a single, simple interface'
  description: Tax-Brain is an integrator model for PSL tax models
  doc_url: http://taxbrain.pslmodels.org/content/intro.html
  dev_url: https://github.com/PSLmodels/Tax-Brain

extra:
  recipe-maintainers:
    - andersonfrailey
