{% set name = "taxbrain" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PSLmodels/Tax-Brain/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4b754011ece47c6af2b7ea293b26383b455b296e4749a637a650bc4a1f8943f3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - taxbrain = taxbrain.cli:cli_main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - taxcalc >=3.0.0
    - behresp >=0.11.0
    - dask
    - bokeh
    - markdown
    - tabulate
    - pypandoc
    - matplotlib-base
    - numpy >=1.14

test:
  imports:
    - taxbrain

about:
  home: https://github.com/PSLmodels/Tax-Brain
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Simple, fast, extensible JSON encoder/decoder for Python
  description: Tax-Brain is an integrator model for PSL tax models
  doc_url: http://taxbrain.pslmodels.org/content/intro.html
  dev_url: https://github.com/PSLmodels/Tax-Brain

extra:
  recipe-maintainers:
    - andersonfrailey
